[[main]]
  name = "Blog"
  url = ""
  weight = -110

[[main]]
  name = "Home"
  url = "https://owenstamp.com"
  weight = -109

# Submenus are done this way: parent -> identifier
#[[main]]
#  name = "Links"
#  identifier = "Links"
#  weight = -108
#[[main]]
  #parent = "Links"
 # name = "LinkedIn"
#  url = "https://www.linkedin.com/"


# social menu links

#[[social]]
 #name = "github"
 #type = "social"
  #weight = 1
 #url = "https://github.com/#"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"